name: 'iOS Vibe Localization'
description: >
  A GitHub Action that translates iOS apps using AI, built on top of string catalogs.
author: 'iOS Vibe Localization'

inputs:
  xcstrings_file_path:
    description: 'Path to the Localizable.xcstrings file.'
    required: false
    default: 'Localizable.xcstrings'
  target_languages:
    description: 'Comma-separated list of language codes to translate into (e.g., es,fr,de).'
    required: true
  github_token:
    description: 'GitHub token for creating branches and pull requests. Must have contents:write and pull-requests:write permissions.'
    required: true
  pr_branch_prefix:
    description: 'Prefix for the pull request branch name.'
    required: false
    default: 'ios-vibe-localization-updates/'
  commit_user_name:
    description: 'Name for git commit user.'
    required: false
    default: 'github-actions[bot]'
  commit_user_email:
    description: 'Email for git commit user.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_message:
    description: 'Commit message for localization updates.'
    required: false
    default: 'i18n: Update translations by iOS Vibe Localization Action'
  pr_title:
    description: 'Title for the pull request.'
    required: false
    default: 'iOS Vibe Localization: Automated Localization Updates'
  pr_body:
    description: 'Body content for the pull request.'
    required: false
    default: 'Automated localization updates by the iOS Vibe Localization Action.'
  openai_model:
    description: 'OpenAI model to use for translations.'
    required: false
    default: 'gpt-4o-mini'
  base_system_prompt:
    description: 'Additional system prompt to provide context for the LLM when translating strings.'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'globe'
  color: 'blue' 